//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class Customer : object
    {
        
        private string AddressField;
        
        private int CustomerIDField;
        
        private string CustomerNameField;
        
        private string EmailIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId
        {
            get
            {
                return this.EmailIdField;
            }
            set
            {
                this.EmailIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sales.ISaleService")]
    public interface ISaleService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/InsertCustomer", ReplyAction="http://tempuri.org/ISaleService/InsertCustomerResponse")]
        bool InsertCustomer(Sales.Customer obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/InsertCustomer", ReplyAction="http://tempuri.org/ISaleService/InsertCustomerResponse")]
        System.Threading.Tasks.Task<bool> InsertCustomerAsync(Sales.Customer obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/GetAllCustomer", ReplyAction="http://tempuri.org/ISaleService/GetAllCustomerResponse")]
        Sales.Customer[] GetAllCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/GetAllCustomer", ReplyAction="http://tempuri.org/ISaleService/GetAllCustomerResponse")]
        System.Threading.Tasks.Task<Sales.Customer[]> GetAllCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/DeleteCustomer", ReplyAction="http://tempuri.org/ISaleService/DeleteCustomerResponse")]
        bool DeleteCustomer(int Cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/DeleteCustomer", ReplyAction="http://tempuri.org/ISaleService/DeleteCustomerResponse")]
        System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int Cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/UpdateCustomer", ReplyAction="http://tempuri.org/ISaleService/UpdateCustomerResponse")]
        bool UpdateCustomer(Sales.Customer obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/UpdateCustomer", ReplyAction="http://tempuri.org/ISaleService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<bool> UpdateCustomerAsync(Sales.Customer obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISaleServiceChannel : Sales.ISaleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SaleServiceClient : System.ServiceModel.ClientBase<Sales.ISaleService>, Sales.ISaleService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SaleServiceClient() : 
                base(SaleServiceClient.GetDefaultBinding(), SaleServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISaleService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaleServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SaleServiceClient.GetBindingForEndpoint(endpointConfiguration), SaleServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaleServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SaleServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaleServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SaleServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool InsertCustomer(Sales.Customer obj)
        {
            return base.Channel.InsertCustomer(obj);
        }
        
        public System.Threading.Tasks.Task<bool> InsertCustomerAsync(Sales.Customer obj)
        {
            return base.Channel.InsertCustomerAsync(obj);
        }
        
        public Sales.Customer[] GetAllCustomer()
        {
            return base.Channel.GetAllCustomer();
        }
        
        public System.Threading.Tasks.Task<Sales.Customer[]> GetAllCustomerAsync()
        {
            return base.Channel.GetAllCustomerAsync();
        }
        
        public bool DeleteCustomer(int Cid)
        {
            return base.Channel.DeleteCustomer(Cid);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int Cid)
        {
            return base.Channel.DeleteCustomerAsync(Cid);
        }
        
        public bool UpdateCustomer(Sales.Customer obj)
        {
            return base.Channel.UpdateCustomer(obj);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCustomerAsync(Sales.Customer obj)
        {
            return base.Channel.UpdateCustomerAsync(obj);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISaleService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISaleService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:61685/SaleService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SaleServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISaleService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SaleServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISaleService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISaleService,
        }
    }
}
